name: "Terraform init/plan"
description: "Init/Plan Terraform witch tfnotify"
inputs:
  name:
    description: "Setup terraform"
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.11

    - name: Install tfnotify
      id: install
      run: |
        sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v0.7.0/tfnotify_linux_amd64.tar.gz
        sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz
    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Plan
      id: plan
      run: terraform plan | tfnotify -config ./.tfnotify/github.yaml plan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
